In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns

#### Importando o dataset

In [2]:
df = pd.read_csv("../dados/dados_brutos/dados_ingressantes.csv")

#### Importando e explorando os dados

In [3]:
df.head(10)

,unica,genero,etnia,idade,necessidade_especial,curso,unidade,sigla_unidade,campus,nivel,modalidade,status,forma_evasao,tipo_evasao,periodo_letivo
0,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.1
1,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.2
2,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2025.1
3,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2022.2
4,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2023.1
5,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2023.2
6,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.1
7,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.2
8,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2025.1
9,cdb29ad33a372918865c535f299b49b0,F,Pardo,22.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2022.2

In [4]:
df.tail()

,unica,genero,etnia,idade,necessidade_especial,curso,unidade,sigla_unidade,campus,nivel,modalidade,status,forma_evasao,tipo_evasao,periodo_letivo
631438,5799d0d93f81ef9c0eba21ac1e9996fe,M,Pardo,22.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.2
631439,5799d0d93f81ef9c0eba21ac1e9996fe,M,Pardo,22.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2025.1
631440,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2022.2
631441,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2023.1
631442,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2023.2

In [5]:
df.shape

(631443, 15)

In [6]:
df.columns

Index(['unica', 'genero', 'etnia', 'idade', 'necessidade_especial', 'curso',
       'unidade', 'sigla_unidade', 'campus', 'nivel', 'modalidade', 'status',
       'forma_evasao', 'tipo_evasao', 'periodo_letivo'],
      dtype='str')

In [7]:
df.isna().sum()

unica                        0
genero                       0
etnia                        0
idade                       20
necessidade_especial    615124
curso                        0
unidade                      0
sigla_unidade                0
campus                       0
nivel                        0
modalidade                   0
status                       0
forma_evasao            631443
tipo_evasao             631443
periodo_letivo               0
dtype: int64

#### Organizando e limpando os dados

In [8]:
df.isna().sum()

unica                        0
genero                       0
etnia                        0
idade                       20
necessidade_especial    615124
curso                        0
unidade                      0
sigla_unidade                0
campus                       0
nivel                        0
modalidade                   0
status                       0
forma_evasao            631443
tipo_evasao             631443
periodo_letivo               0
dtype: int64

In [9]:
df.head()

,unica,genero,etnia,idade,necessidade_especial,curso,unidade,sigla_unidade,campus,nivel,modalidade,status,forma_evasao,tipo_evasao,periodo_letivo
0,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.1
1,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2024.2
2,31d121f5c9635e7e87b38df5c642145f,M,Pardo,21.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2025.1
3,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2022.2
4,fdbc2e0d796f2bec27d5494b89eb15ee,F,Pardo,23.0,NaN,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,Campus Arapiraca,LICENCIATURA PLENA,Presencial,matriculado,NaN,NaN,2023.1

In [10]:
df = df.dropna(subset=['idade'])

In [12]:
df.isna().sum()

unica             0
genero            0
etnia             0
idade             0
curso             0
unidade           0
sigla_unidade     0
campus            0
nivel             0
modalidade        0
status            0
periodo_letivo    0
dtype: int64

In [14]:
df.columns

Index(['unica', 'genero', 'etnia', 'idade', 'curso', 'unidade',
       'sigla_unidade', 'campus', 'nivel', 'modalidade', 'status',
       'periodo_letivo'],
      dtype='str')

In [15]:
df = df.drop(['unica'], axis=1)

In [45]:
df.columns

Index(['genero', 'etnia', 'idade', 'curso', 'unidade', 'sigla_unidade',
       'campus', 'nivel', 'modalidade', 'status', 'periodo_letivo',
       'nome_curso', 'turno', 'grau', 'regime'],
      dtype='str')

In [46]:
cursos = df['curso'].str.split(' - ', expand=True)

In [48]:
df['nome_curso'] = cursos[0]
df['campus'] = cursos [1]
df['turno'] = cursos [2]
df['modalidade'] = cursos [3]
df['grau'] = cursos [4]
df['regime'] = cursos [5]
df['codigo_curso'] = cursos [6]

In [50]:
df.head(3)

,genero,etnia,idade,curso,unidade,sigla_unidade,campus,nivel,modalidade,status,periodo_letivo,nome_curso,turno,grau,regime,codigo_curso
0,M,Pardo,21.0,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,CAMPUS ARAPIRACA,LICENCIATURA PLENA,PRESENCIAL,matriculado,2024.1,QUÍMICA,MATUTINO,LICENCIATURA PLENA,SEMESTRAL,(102156)
1,M,Pardo,21.0,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,CAMPUS ARAPIRACA,LICENCIATURA PLENA,PRESENCIAL,matriculado,2024.2,QUÍMICA,MATUTINO,LICENCIATURA PLENA,SEMESTRAL,(102156)
2,M,Pardo,21.0,QUÍMICA - CAMPUS ARAPIRACA - MATUTINO - PRESEN...,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,CA,CAMPUS ARAPIRACA,LICENCIATURA PLENA,PRESENCIAL,matriculado,2025.1,QUÍMICA,MATUTINO,LICENCIATURA PLENA,SEMESTRAL,(102156)

In [51]:
df.columns

Index(['genero', 'etnia', 'idade', 'curso', 'unidade', 'sigla_unidade',
       'campus', 'nivel', 'modalidade', 'status', 'periodo_letivo',
       'nome_curso', 'turno', 'grau', 'regime', 'codigo_curso'],
      dtype='str')

In [62]:
df_organizado = df[
    [

        # Informações do curso
        'nome_curso',
        'grau',
        'turno',
        'modalidade',
        'regime',
        
        # Perfil do aluno
        'genero',
        'idade',
        'etnia',

        # Localização
        'campus',
        'unidade',
        # Tempo
        'periodo_letivo',

    ]
]

In [63]:
dados_ingressantes = df_organizado

In [64]:
dados_ingressantes.head()

,nome_curso,grau,turno,modalidade,regime,genero,idade,etnia,campus,unidade,periodo_letivo
0,QUÍMICA,LICENCIATURA PLENA,MATUTINO,PRESENCIAL,SEMESTRAL,M,21.0,Pardo,CAMPUS ARAPIRACA,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,2024.1
1,QUÍMICA,LICENCIATURA PLENA,MATUTINO,PRESENCIAL,SEMESTRAL,M,21.0,Pardo,CAMPUS ARAPIRACA,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,2024.2
2,QUÍMICA,LICENCIATURA PLENA,MATUTINO,PRESENCIAL,SEMESTRAL,M,21.0,Pardo,CAMPUS ARAPIRACA,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,2025.1
3,QUÍMICA,LICENCIATURA PLENA,MATUTINO,PRESENCIAL,SEMESTRAL,F,23.0,Pardo,CAMPUS ARAPIRACA,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,2022.2
4,QUÍMICA,LICENCIATURA PLENA,MATUTINO,PRESENCIAL,SEMESTRAL,F,23.0,Pardo,CAMPUS ARAPIRACA,COORDENAÇÃO DOS CURSOS ACADÊMICOS - SEDE ARAPI...,2023.1

In [65]:
dados_ingressantes.to_csv("../dados/dados_preprocessados/ingressantes_ufal.csv")