In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns

### Carregando os dados

In [2]:
df_evasao = pd.read_csv("../dados/dados_brutos/dados_evasao.csv")

In [3]:
df_evasao.head()

,unica,genero,etnia,idade,necessidade_especial,curso,unidade,sigla_unidade,campus,nivel,modalidade,status,forma_evasao,tipo_evasao,periodo_letivo
0,8644b2dd25605978bc4b557b81ca9d95,M,Pardo,41.0,NaN,MATEMÁTICA - CAMPUS MACEIÓ - VESPERTINO - PRES...,INSTITUTO DE MATEMÁTICA,IM,Campus Maceió,BACHARELADO,Presencial,evadido,jubilamento,permanente,2013.1
1,3e775d20a1b0ce64775eb63e7e0e7d03,M,Branco,34.0,NaN,MATEMÁTICA - CAMPUS MACEIÓ - VESPERTINO - PRES...,INSTITUTO DE MATEMÁTICA,IM,Campus Maceió,BACHARELADO,Presencial,evadido,jubilamento,permanente,2015.1
2,1f543ad53a8978c8276b58a582d53ca5,M,Branco,47.0,NaN,EDUCAÇÃO FÍSICA - CAMPUS MACEIÓ - NOTURNO - PR...,INSTITUTO DE EDUCAÇÃO FÍSICA E ESPORTE,IEFE,Campus Maceió,BACHARELADO,Presencial,evadido,jubilamento,permanente,2017.2
3,96c73aff48bdb1b56736d1623bf29d3c,M,Branco,34.0,NaN,METEOROLOGIA - CAMPUS MACEIÓ - MATUTINO E VESP...,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,Campus Maceió,BACHARELADO,Presencial,evadido,jubilamento,permanente,2015.1
4,681885ab2396f1dbbe92890602da0f58,F,Pardo,38.0,Deficiência Auditiva,METEOROLOGIA - CAMPUS MACEIÓ - MATUTINO E VESP...,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,Campus Maceió,BACHARELADO,Presencial,evadido,desistência,permanente,2010.1

### Limpeza e organização dos dados

In [4]:
df_evasao.isna().sum()

unica                       0
genero                      0
etnia                       0
idade                       5
necessidade_especial    51129
curso                       0
unidade                     0
sigla_unidade               0
campus                      0
nivel                       0
modalidade                  0
status                      0
forma_evasao                0
tipo_evasao                 0
periodo_letivo              0
dtype: int64

In [5]:
df_evasao['idade'].describe

<bound method NDFrame.describe of 0        41.0
1        34.0
2        47.0
3        34.0
4        38.0
         ...
52388    41.0
52389    34.0
52390    38.0
52391    35.0
52392    35.0
Name: idade, Length: 52393, dtype: float64>

In [6]:
df_evasao = df_evasao.dropna(subset=['idade'])

In [7]:
df_evasao['necessidade_especial'].value_counts(dropna=False)

necessidade_especial
NaN                                                                                                                                             51124
Baixa Visão                                                                                                                                       497
Altas Habilidades e Superdotação                                                                                                                  216
Deficiência Física                                                                                                                                135
Cegueira                                                                                                                                           96
Deficiência Auditiva                                                                                                                               94
Transtornos do Desenvolvimento da Aprendizagem                                                                                                     55
Transtorno do Espectro Autista                                                                                                                     29
Deficiência Intelectual                                                                                                                            28
Deficiência Múltipla                                                                                                                               12
Deficiência Sensorial                                                                                                                              12
Deficiência não listada                                                                                                                            11
Surdez                                                                                                                                              8
Surdocegueira                                                                                                                                       6
Transtorno do Espectro Autista + Transtorno do Déficit de Atenção e Hiperatividade                                                                  6
Transtornos do Desenvolvimento Intelectual                                                                                                          6
Altas Habilidades e Superdotação + Transtorno do Déficit de Atenção e Hiperatividade + Transtornos do Neurodesenvolvimento Não Especificados        5
Transtorno do Déficit de Atenção e Hiperatividade                                                                                                   5
Deficiência Intelectual + Deficiência Mental                                                                                                        4
Deficiência Mental                                                                                                                                  4
Deficiência Mental + Transtornos do Neurodesenvolvimento Não Especificados                                                                          4
Baixa Visão + Transtorno do Déficit de Atenção e Hiperatividade                                                                                     3
Deficiência não listada + Transtornos do Desenvolvimento da Aprendizagem                                                                            3
Cegueira + Baixa Visão                                                                                                                              3
Transtorno do Espectro Autista + Altas Habilidades e Superdotação                                                                                   2
Transtorno do Espectro Autista + Altas Habilidades e Superdotação + Transtornos do Neurodesenvolvimento Não Especificados                           2
Surdez + Deficiência Auditiva                                                                                                                       2
Deficiência Física + Deficiência Intelectual                                                                                                        2
Deficiência Intelectual + Transtornos do Desenvolvimento Intelectual                                                                                2
Transtorno do Espectro Autista + Transtornos do Desenvolvimento da Aprendizagem                                                                     1
Baixa Visão + Surdez                                                                                                                                1
Transtorno do Espectro Autista + Transtornos do Neurodesenvolvimento Não Especificados                                                              1
Cegueira + Deficiência Física + Deficiência não listada                                                                                             1
Transtornos do Desenvolvimento Intelectual + Transtornos do Desenvolvimento da Aprendizagem                                                         1
Cegueira + Deficiência Física                                                                                                                       1
Deficiência Física + Deficiência não listada                                                                                                        1
Baixa Visão + Transtorno do Espectro Autista + Transtorno do Déficit de Atenção e Hiperatividade                                                    1
Baixa Visão + Transtornos do Desenvolvimento Intelectual                                                                                            1
Transtorno do Déficit de Atenção e Hiperatividade + Transtornos do Neurodesenvolvimento Não Especificados                                           1
Transtornos do Neurodesenvolvimento + Transtorno do Déficit de Atenção e Hiperatividade                                                             1
Baixa Visão + Deficiência não listada                                                                                                               1
Name: count, dtype: int64

In [8]:
df_evasao['necessidade_especial'] = (
    df_evasao['necessidade_especial']
    .fillna('Nenhuma')
)

In [9]:
div_var_cursos = df_evasao['curso'].str.split(' - ', expand=True)

In [10]:
df_evasao['nome_curso'] = div_var_cursos[0]
df_evasao['campus'] = div_var_cursos [1]
df_evasao['turno'] = div_var_cursos [2]
df_evasao['modalidade'] = div_var_cursos [3]
df_evasao['grau'] = div_var_cursos [4]
df_evasao['regime'] = div_var_cursos [5]

In [11]:
df_evasao_processado = df_evasao[
    [

        # Informações do curso
        'nome_curso',
        'grau',
        'turno',
        'modalidade',
        'regime',
        'nivel',
        
        # Perfil do aluno
        'genero',
        'idade',
        'etnia',
        'necessidade_especial',

        # Localização
        'campus',
        'unidade',
        'sigla_unidade',

        # Situação acadêmica
        'status',
        'forma_evasao',
        'tipo_evasao',

        # Tempo
        'periodo_letivo',

    ]
]

In [12]:
df_evasao_processado.head(10)

,nome_curso,grau,turno,modalidade,regime,nivel,genero,idade,etnia,necessidade_especial,campus,unidade,sigla_unidade,status,forma_evasao,tipo_evasao,periodo_letivo
0,MATEMÁTICA,BACHARELADO,VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,41.0,Pardo,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE MATEMÁTICA,IM,evadido,jubilamento,permanente,2013.1
1,MATEMÁTICA,BACHARELADO,VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,34.0,Branco,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE MATEMÁTICA,IM,evadido,jubilamento,permanente,2015.1
2,EDUCAÇÃO FÍSICA,BACHARELADO,NOTURNO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,47.0,Branco,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE EDUCAÇÃO FÍSICA E ESPORTE,IEFE,evadido,jubilamento,permanente,2017.2
3,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,34.0,Branco,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,jubilamento,permanente,2015.1
4,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,F,38.0,Pardo,Deficiência Auditiva,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,desistência,permanente,2010.1
5,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,34.0,Branco,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,jubilamento,permanente,2015.1
6,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,36.0,Pardo,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,canc. por reopcao,permanente,2011.2
7,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,36.0,Pardo,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,canc. por reopcao,permanente,2012.1
8,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,35.0,Branco,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,jubilamento,permanente,2015.1
9,METEOROLOGIA,BACHARELADO,MATUTINO E VESPERTINO,PRESENCIAL,SEMESTRAL,BACHARELADO,M,38.0,Negro,Nenhuma,CAMPUS MACEIÓ,INSTITUTO DE CIÊNCIAS ATMOSFÉRICAS,ICAT,evadido,jubilamento,permanente,2014.1

In [13]:
df_evasao_processado.to_csv("../dados/dados_preprocessados/evasao_ufal.csv")